myapp/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, lm
from flask.ext.login import UserMixin
import ldap

class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(16), index=True, unique=True)
	password_hash = db.Column(db.String(64))

	def set_password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	@staticmethod
	def try_login(username, password):
		conn = ldap.initialize('ldap://ldap.example.com')
		conn.protocol_version = ldap.VERSION3
		conn.simple_bind_s('uid=%s,ou=people,dc=example,dc=com' %username,password)
		print "connected by ", username
	
	def is_authenticated(self):
		return True
	def is_active(self):
		return True
	def is_anonymous(self):
		return False
	def get_id(self):
		return unicode(self.id)

	@staticmethod
	def register(username, password):
		user = User(username=username)
		user.set_password(password)
		db.session.add(user)
		db.session.commit()

	def __repr__(self):
		return '<User {0}>'.format(self.username)

@lm.user_loader
def load_user(id):
	return User.query.get(int(id))

myapp/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length, DataRequired

class LoginForm(Form):
	username = StringField('Username', validators=[Required(), Length(3,16)])
	password = PasswordField('Password', validators=[Required()])
	remember_me = BooleanField('Remember me')
	submit = SubmitField('Submit')

class CheckUserForm(Form):
	checkusername = StringField('Please enter userid', validators=[DataRequired(), Length(3,16)])
	submit = SubmitField('Submit')

myapp/__init__.py
import os
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager
from flask.ext.sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'

def create_app(config_name):
	#Create application instance
	app = Flask(__name__)
	
	#import configuration
	cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
	app.config.from_pyfile(cfg)
	
	#initialize extensions
	bootstrap.init_app(app)
	lm.init_app(app)
	db.init_app(app)

	#import blueprints
	from .main import main as main_blueprint 
	app.register_blueprint(main_blueprint)

	return app

myapp/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

myapp/main/routes.py
from . import main
from flask import render_template, redirect, url_for, request, g
from flask.ext.login import login_required, login_user, logout_user, current_user
from .forms import LoginForm, CheckUserForm
from ..models import User
import ldap
from .localuser import localUserCheck, ldapAuthQuery

@main.route('/')
def index():
	return render_template('index.html')

@main.route('/login', methods=['GET','POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		username = form.username.data
		password = form.password.data

		try: 
			User.try_login(username,password)
		except ldap.INVALID_CREDENTIALS:
			return redirect(url_for('main.login', **request.args))
		
		user = User.query.filter_by(username=form.username.data).first()
		if not user:
			User.register(username,password)
		login_user(user, form.remember_me.data)
		return redirect(request.args.get('next') or url_for('main.index'))
	return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
	logout_user()
	return redirect(url_for('main.index'))

@main.route('/checkuser', methods=['GET','POST'])
@login_required
def checkuser():
	form = CheckUserForm()
	if form.validate_on_submit():
		name = form.checkusername.data
		pw_file_id_details = localUserCheck(name)		
		pw_file_id_details = localUserCheck(name)		
		ldap_result = ldapAuthQuery(name)
		return render_template('useridresult.html', pw_file_id_details = pw_file_id_details, ldap_result=ldap_result)
		form.checkusername.data = ''
	return render_template('checkuser.html', form=form)

myapp/templates/base.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}User Information{% endblock %}

{% block navbar %}
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<a class="navbar-brand" href="{{ url_for('main.index')}}">User Information</a>
			<ul class="nav navbar-nav">
				<li><a href="{{ url_for('main.index') }}">Home</a></li>
				<li><a href="{{ url_for('main.checkuser') }}">Check User</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					{% if current_user.is_authenticated() %}
						<a href="{{ url_for('main.logout') }}">Logout</a>
					{% else %}
						<a href="{{ url_for('main.login') }}">Login</a>						
					{% endif %}
				</li>
			</ul>
		</div>
	</nav>
{% endblock %}

{% block content %}
	<div class="container">
		{% block page_content %}{% endblock %}
	</div>
	{% block footer %}
		<footer class="footer navbar-fixed-bottom">
		    <div class="container">
			<center><p class="text-muted">copyright &copy; 2015</p></center>
		    </div>
		</footer>
    	{% endblock %}
{% endblock %}

myapp/templates/checkuser.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}                            
                                                                    
{% block title %}User Information{% endblock %}                     
                                                                    
{% block page_content %}                                            
<body>                                                              
    <div class="container">                                         
        <div class="row well">                                      
            <div class="col-md-3"> {{ wtf.quick_form(form) }} </div>
        <div/>                                                      
    </div>                                                          
</body>                                                             
{% endblock %}                                                      

myapp/templates/index.html
{% extends 'base.html' %}
{% block title %}User Information{% endblock %}
{% block page_content %}
<body>
    <div class='container'>
        <div class='row well text-center'>
            <div class='col-md-12'>
                <h1>User Information</h1>
                <p>Find User related information for unix systems.</p>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-4'>
                <h2> Introduction </h2>
                <p>This helps team perform basic Unix Operations.</p>
                <p>Find out information about the userid.</p>
		<p>{% if not current_user.is_authenticated() %}Please Login.{% endif %}</p>
            </div>
            <div class='col-md-4'>
                <img src='static/images/userid.png' alt='profile'/>
            </div>
            <div class='col-md-4 center'>
                <h2>Identify</h2>
                <li>Active Users</li>
                <li>Disabled Password</li>
                <li>Re-Hire Account</li>
                <li>Non-Existent Users</li>
            </div>
        </div>
    </div>
</body>
{% endblock %}

myapp/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}User Information{% endblock %}

{% block page_content %}
	<h1>Login</h1>
	<div class="row">
		<div class="col-md-3">
			{{ wtf.quick_form(form) }}
		</div>
	</div>
{% endblock %}

myapp/templates/useridresult.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}   

{% block title %}User Information{% endblock %}                                      
                                                                                     
{% block page_content %}                                                             
<body>                                                                               
    <div class="container">                                                          
        <div class="row well">                                                       
            <div class="col-md-5 col-md-offset-4">                                   
            <h3>Unix Server</h3>                                                     
            {% if pw_file_id_details %}                                                           
               {% if pw_file_id_details[1] | first == 'X'  %}                                     
                   ID {{ pw_file_id_details[0] }} exists on server, but is prefixed with X. 
               {% elif pw_file_id_details[2] == 'DISABLED' %}                                     
                   {{ pw_file_id_details[1] }} ID exists, but password is DISABLED.               
               {% elif pw_file_id_details[1] %}                                                   
                   {{ pw_file_id_details[1] }} ID exists.</div>                                   
               {% elif pw_file_id_details[0] is defined and pw_file_id_details[1] is not defined %}            
                   ID {{ pw_file_id_details[0] }} doesn't exist.                                  
               {% endif %}                                                           
            {% else %}                                                               
               Unable to find user.                                                  
            {% endif %}                                                              
            </div>                                                                   
        </div>                                                                       
	<div class="row ">
		<div class="col-md-4">                                    
			<h3>OpenLDAP</h3>                                         
    			<table class="table table-bordered table-striped">    
        			{% for element in ldap_result %}
					{% if element %}
					<tr><th>Attribute</th><th>Value</th>
					<tr>
						{% for key, value in element.iteritems() %}
							<td>{{ key }}</td><td>{{ value[0] }}</td>
						<tr>
						{% endfor %}
					{% endif %}
				{% endfor %}
    			</table>                                              
		</div>                                                    
    </div>
</body>
{% endblock %}